---
title: "project"
author: "Boya"
date: "11/9/2019"
output: html_document
---
##setup
```{r}
install.packages("rjson")
library(tidyverse)
library("rjson")
```

##Read in data
```{r}
data <- fromJSON(file = "/Users/liboya/Desktop/newsubmission.json")
names <- names(data)
df<-data.frame("a","b","c","d","e","f")
names(df)<-c("id","demo","time","score","upvote_ratio", "rates")
for (val in names){
  de <- as.data.frame(data$val)
  df <- rbind(df,de)
}
  
  
{de <- data.frame(data$val)[2,]
df <- rbind(df,de)
}
```

## demographics
```{r}
#get age(numbers) and gender(character)
data$gender <- gsub('[0-9]+', '', data$demo)
data$age <- as.numeric(gsub('[A-Z]+', '', data$demo))
table(data$gender)
summarise(data$age)
#cleaning gender
data %<>%
  if (gender!="F" & gender!="M") {
    gender=NA
  }
#frequency table of gender
table(newdemo$gender)
#summarise the mean of age in different gender ggroup
data %>%
  group_by(gender)%>%
  summarise(mean_age = mean(age, na.rm = T))
#plot histogram
data %>%
ggplot() +
  geom_histogram(mapping=aes(x=age, fill=gender, color=gender),binwidth=1, position="identity",alpha=0.4)+ 
  geom_vline(aes(xintercept=mean(age),group=gnder, color=gender), linetype="dashed", size=0.5)
```

## Including Plots
Lastly, we delete stopwords using a stopword lexicon from the `tidytext` package. 
```{r}
nrow(keywords_clean)

stopwds <- get_stopwords("en")
keywords_cleaner <- keywords_clean %>%
  anti_join(stopwds)

nrow(keywords_cleaner)
```

We can now plot the top 15 words based on the cleaned tweet text.

```{r}
keywords_cleaner %>%
  count(word, sort = TRUE) %>%
  top_n(15) %>%
  mutate(word = reorder(word, n)) %>%
  ggplot() +
  geom_col(aes(x = word, y = n)) +
  coord_flip()
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
